version: 2.1

orbs:
  aws-eks: circleci/aws-eks@2.2.0
  kubernetes: circleci/kubernetes@1.2.0

jobs:
  lint:
    docker:
    # Use the same Docker base as the project
      - image: python:3.7.17
    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: test command
          command: |
            ls -lart

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install
            # Install hadolint
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
  
      # run lint!
      - run:
          name: run lint
          command: |
            . venv/bin/activate
            make lint

  build:
    docker:
      - image: cimg/python:3.11.4
    parameters:
      cluster-name:
        description: |
          Name of the EKS cluster
        type: string
        default: "CapstoneEKS-rwcf1oiLrV5T"
      aws-region:
        description: |
          AWS region
        type: string
        default: "us-east-1"
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - run:
          name: Install dependencies
          command: |
            sudo apt install -y tar gzip curl
      - kubernetes/install-kubectl
      - run:
          name: Configure variable
          command: |
            echo AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID >> .env
            echo AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY >> .env
            echo DOCKER_HUB_PASSWORD=$DOCKER_HUB_PASSWORD >> .env
            echo DOCKER_HUB_USERNAME=$DOCKER_HUB_USERNAME >> .env
            cat .env
      - run:
          name: Docker login
          command: |
            docker login -u "$DOCKER_HUB_USERNAME" -p $(echo "$DOCKER_HUB_PASSWORD")
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i caches/project-5.tar | true
      - run:
          name: Build application Docker image
          command: docker build --cache-from=project-5 -t project-5 .
      - run:
          name: Save Docker image layer cache
          command: |
            chmod -R 777 ../
            mkdir -p caches
            docker save -o caches/project-5.tar project-5
      - run:
          name: Push Docker Image
          command: |
            docker tag project-5 tintrandn/project-5
            docker push tintrandn/project-5
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
          aws-region: << parameters.aws-region >>
          install-kubectl: true
      - kubernetes/create-or-update-resource:
          resource-file-path: ./kubernetes/deployment.yml
          resource-name: deployment/project-5
          get-rollout-status: false
          show-kubectl-command: true
      - kubernetes/create-or-update-resource:
          resource-file-path: ./kubernetes/aws-authen-cm.yml
          resource-name: configmap/aws-auth

workflows:
  default:
    jobs:
      - lint
      - build:
          aws-region: $AWS_DEFAULT_REGION
          filters:
            branches:
              only:
                - main